version: 1
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy to Cyclic.sh
          command: cyclic deployment create --name "TEST-BACKEND-MASTER" --path /path/to/your/app
